name: AI Weather Summary Generation

# Cohere AI weather analysis for Singapore weather data
# Generates AI summaries for overall weather conditions
# Cohere API key verified working - final test

on:
  # schedule: # DISABLED - On-demand only system
    # # Run every 15 minutes for real-time AI analysis updates  
    # - cron: '*/15 * * * *'
  
  workflow_dispatch:
    inputs:
      force_analysis:
        description: 'Force AI analysis even if daily limit reached'
        type: boolean
        default: true
  
  push:
    branches: 
      - main
    paths:
      - 'scripts/ai-weather-summary.js'
      - '.github/workflows/ai-weather-summary.yml'
      - 'test-cohere.trigger'

env:
  NODE_ENV: production

jobs:
  weather-summary-generation:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          echo "📦 Installing dependencies..."
          npm ci
          echo "✅ Dependencies installed successfully"

      - name: Verify environment
        run: |
          echo "🔍 Environment verification:"
          echo "Node.js version: $(node --version)"
          echo "NPM version: $(npm --version)"
          echo "Working directory: $(pwd)"
          echo "Files in scripts/:"
          ls -la scripts/ || echo "No scripts directory found"
          echo "Weather data file exists:"
          ls -la data/weather/latest.json || echo "No weather data file found"
          echo "Test scripts available:"
          ls -la scripts/test-* 2>/dev/null || echo "No test scripts found"

      - name: Test Cohere API Connection
        env:
          COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
        run: |
          echo "🧪 Testing Cohere API connection..."
          node scripts/test-cohere-api.js

      - name: Run AI Weather Summary Generation
        env:
          COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
          FORCE_ANALYSIS: ${{ inputs.force_analysis || 'false' }}
        run: |
          echo "🤖 Starting Cohere AI weather summary generation..."
          echo "Force analysis: ${FORCE_ANALYSIS}"
          echo "API key status: ${{ secrets.COHERE_API_KEY && 'SET' || 'NOT_SET' }}"
          node scripts/ai-weather-summary.js

      - name: Commit AI weather summary results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          if [ -f "data/weather-summary/latest.json" ]; then
            git add data/weather-summary/
            git commit -m "feat: Update AI weather summary data

            🤖 Generated with [Claude Code](https://claude.ai/code)
            
            Co-Authored-By: Claude <noreply@anthropic.com>" || exit 0
            git push
            echo "✅ AI weather summary data committed successfully"
          else
            echo "⚠️ No AI weather summary data generated"
          fi