name: Simple AI Analysis

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # 6시간마다 실행 (하루 4회)
  push:
    branches: [ main ]
    paths: 
      - '.github/workflows/simple-ai-analysis.yml'

jobs:
  analyze:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install axios

      - name: Simple AI Analysis
        env:
          COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
        run: |
          node << 'EOF'
          const fs = require('fs');
          const axios = require('axios');
          
          (async () => {
          console.log('🤖 Starting Simple AI Analysis...');
          
          const cohereApiKey = process.env.COHERE_API_KEY;
          const useRealAI = !!cohereApiKey;
          
          console.log('API Key available:', useRealAI);
          
          // Simple priority cameras
          const priorityCameras = ['6710', '2701', '2703', '1701', '4712'];
          const analysisResults = {};
          
          for (const cameraId of priorityCameras) {
            console.log(`Analyzing camera ${cameraId}...`);
            
            const currentTime = new Date();
            const isRushHour = (currentTime.getHours() >= 7 && currentTime.getHours() <= 9) || 
                              (currentTime.getHours() >= 17 && currentTime.getHours() <= 19);
            
            let analysis;
            
            if (useRealAI) {
              try {
                console.log('Using Cohere API...');
                
                const response = await axios.post('https://api.cohere.ai/v1/generate', {
                  model: 'command',
                  prompt: `Singapore traffic camera ${cameraId} analysis. Current time: ${currentTime.toISOString()}. Rush hour: ${isRushHour}. 
                  
                  Provide a JSON response with:
                  {
                    "weather_condition": "맑음 or 흐림 or 부분적으로 흐림",
                    "traffic_status": "교통 원활 or 교통 혼잡 or 교통 정체중",
                    "vehicle_flow": "빠름 or 보통 or 느림",
                    "confidence": 0.85
                  }`,
                  max_tokens: 200,
                  temperature: 0.3
                }, {
                  headers: {
                    'Authorization': `Bearer ${cohereApiKey}`,
                    'Content-Type': 'application/json'
                  },
                  timeout: 10000
                });
                
                const responseText = response.data.generations[0].text.trim();
                console.log('Cohere response:', responseText);
                
                // Try to parse JSON
                const jsonMatch = responseText.match(/\{[\s\S]*\}/);
                if (jsonMatch) {
                  analysis = JSON.parse(jsonMatch[0]);
                } else {
                  throw new Error('No JSON in response');
                }
                
                analysis.ai_model = 'Cohere Command API';
                
              } catch (error) {
                console.log('Cohere API error:', error.message);
                
                // Fallback
                analysis = {
                  weather_condition: '맑음',
                  traffic_status: isRushHour ? '교통 혼잡' : '교통 원활',
                  vehicle_flow: isRushHour ? '느림' : '보통',
                  confidence: 0.75,
                  ai_model: 'Cohere Command API (Fallback)'
                };
              }
            } else {
              // No API key
              analysis = {
                weather_condition: '맑음',
                traffic_status: '정보 없음',
                vehicle_flow: '알 수 없음',
                confidence: 0.70,
                ai_model: 'Simulation'
              };
            }
            
            // Add metadata
            analysis.analysis_timestamp = currentTime.toISOString();
            analysis.camera_id = cameraId;
            analysis.visibility = '양호';
            analysis.road_conditions = '건조';
            
            analysisResults[cameraId] = analysis;
            
            // Rate limiting
            await new Promise(resolve => setTimeout(resolve, 1000));
          }
          
          // Save results
          if (!fs.existsSync('data')) {
            fs.mkdirSync('data', { recursive: true });
          }
          if (!fs.existsSync('data/ai-analysis')) {
            fs.mkdirSync('data/ai-analysis', { recursive: true });
          }
          
          const outputData = {
            timestamp: new Date().toISOString(),
            total_analyzed: Object.keys(analysisResults).length,
            analysis_method: useRealAI ? 'Cohere Command API' : 'Simulation',
            cohere_api_available: useRealAI,
            cameras: analysisResults
          };
          
          fs.writeFileSync('data/ai-analysis/latest.json', JSON.stringify(outputData, null, 2));
          
          console.log('✅ Analysis completed successfully');
          console.log('Cameras analyzed:', Object.keys(analysisResults).length);
          })().catch(error => {
            console.error('❌ Simple AI Analysis failed:', error);
            process.exit(1);
          });
          
          EOF

      - name: Commit results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          if [ -n "$(git status --porcelain)" ]; then
            git add data/ai-analysis/latest.json
            git commit -m "feat: Update AI traffic analysis results (Simple)

            🤖 Generated with Simple AI Analysis workflow"
            git push
            echo "✅ Results committed and pushed"
          else
            echo "ℹ️ No changes to commit"
          fi